# Generated by Django 4.1.2 on 2022-10-19 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facts',
            options={'ordering': ['-published'], 'verbose_name': 'Факт', 'verbose_name_plural': 'Факты'},
        ),
        migrations.AddField(
            model_name='facts',
            name='published',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Опубликовано'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facts',
            name='fact',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
