# Generated by Django 4.1.2 on 2022-10-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_facts_options_facts_published_alter_facts_fact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facts',
            options={'ordering': ['published'], 'verbose_name': 'Факт', 'verbose_name_plural': 'Факты'},
        ),
    ]
